// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrvk7t7FDWLOYFLfq-v99iocockMXf20',
    appId: '1:653303182678:web:18e5a4bf47a5235fffd2f7',
    messagingSenderId: '653303182678',
    projectId: 'petrolaxweb',
    authDomain: 'petrolaxweb.firebaseapp.com',
    storageBucket: 'petrolaxweb.appspot.com',
    measurementId: 'G-WXNWBVLRMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq7p0TksmXnjDUXgN21anxYGfSgg8hg9M',
    appId: '1:653303182678:android:4d6c68a1191a39a7ffd2f7',
    messagingSenderId: '653303182678',
    projectId: 'petrolaxweb',
    storageBucket: 'petrolaxweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW3BGVXzFAcAk2CX5hJUbcMmMMIueqqv4',
    appId: '1:653303182678:ios:6ce440e6e9349f45ffd2f7',
    messagingSenderId: '653303182678',
    projectId: 'petrolaxweb',
    storageBucket: 'petrolaxweb.appspot.com',
    iosBundleId: 'com.example.flutterWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW3BGVXzFAcAk2CX5hJUbcMmMMIueqqv4',
    appId: '1:653303182678:ios:6ce440e6e9349f45ffd2f7',
    messagingSenderId: '653303182678',
    projectId: 'petrolaxweb',
    storageBucket: 'petrolaxweb.appspot.com',
    iosBundleId: 'com.example.flutterWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIrvk7t7FDWLOYFLfq-v99iocockMXf20',
    appId: '1:653303182678:web:7acaaab267b8caa1ffd2f7',
    messagingSenderId: '653303182678',
    projectId: 'petrolaxweb',
    authDomain: 'petrolaxweb.firebaseapp.com',
    storageBucket: 'petrolaxweb.appspot.com',
    measurementId: 'G-9VW4HV0RH9',
  );
}
